
python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_silvio4/ -l 971 --xsec 200 --gen-pdf modexp       --fit-pdf silvio4  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_modexp_silvio4 &
python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_silvio4/ -l 971 --xsec 200 --gen-pdf fiveparam --fit-pdf silvio4  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_fiveparam_silvio4 &
python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_silvio4/ -l 971 --xsec 200 --gen-pdf atlas         --fit-pdf silvio4  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas_silvio4 &
python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_silvio4/ -l 971 --xsec 200 --gen-pdf atlas6       --fit-pdf silvio4  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas6_silvio4 &
python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_silvio4/ -l 971 --xsec 200 --gen-pdf silvio5     --fit-pdf silvio4  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio5_silvio4 &
python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_silvio4/ -l 971 --xsec 200 --gen-pdf silvio6     --fit-pdf silvio4  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio6_silvio4 &
python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio4_silvio4/ -l 971 --xsec 200 --gen-pdf silvio4     --fit-pdf silvio4  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio4_silvio4 &

#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_silvio6/ -l 971 --xsec 200 --gen-pdf modexp       --fit-pdf silvio6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_modexp_silvio6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_silvio6/ -l 971 --xsec 200 --gen-pdf fiveparam --fit-pdf silvio6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_fiveparam_silvio6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_silvio6/ -l 971 --xsec 200 --gen-pdf atlas         --fit-pdf silvio6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas_silvio6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_silvio6/ -l 971 --xsec 200 --gen-pdf atlas6       --fit-pdf silvio6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas6_silvio6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_silvio6/ -l 971 --xsec 200 --gen-pdf silvio5     --fit-pdf silvio6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio5_silvio6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_silvio6/ -l 971 --xsec 200 --gen-pdf silvio6     --fit-pdf silvio6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio6_silvio6 &



#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_silvio5/ -l 971 --xsec 200 --gen-pdf modexp       --fit-pdf silvio5  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_modexp_silvio5 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_silvio5/ -l 971 --xsec 200 --gen-pdf fiveparam --fit-pdf silvio5  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_fiveparam_silvio5 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_silvio5/ -l 971 --xsec 200 --gen-pdf atlas         --fit-pdf silvio5  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas_silvio5 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_silvio5/ -l 971 --xsec 200 --gen-pdf atlas6       --fit-pdf silvio5  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas6_silvio5 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_silvio5/ -l 971 --xsec 200 --gen-pdf silvio5     --fit-pdf silvio5  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio5_silvio5 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_silvio5/ -l 971 --xsec 200 --gen-pdf silvio6     --fit-pdf silvio5  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio6_silvio5 &

#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_atlas6/ -l 971 --xsec 200 --gen-pdf modexp       --fit-pdf atlas6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_modexp_atlas6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_atlas6/ -l 971 --xsec 200 --gen-pdf fiveparam --fit-pdf atlas6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_fiveparam_atlas6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_atlas6/ -l 971 --xsec 200 --gen-pdf atlas         --fit-pdf atlas6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas_atlas6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_atlas6/ -l 971 --xsec 200 --gen-pdf atlas6       --fit-pdf atlas6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas6_atlas6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_atlas6/ -l 971 --xsec 200 --gen-pdf silvio5     --fit-pdf atlas6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio5_atlas6 &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_atlas6/ -l 971 --xsec 200 --gen-pdf silvio6     --fit-pdf atlas6  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio6_atlas6 &


#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_fiveparam/ -l 971 --xsec 200 --gen-pdf modexp       --fit-pdf fiveparam  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_modexp_fiveparam &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_fiveparam/ -l 971 --xsec 200 --gen-pdf fiveparam --fit-pdf fiveparam  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_fiveparam_fiveparam &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_fiveparam/ -l 971 --xsec 200 --gen-pdf atlas         --fit-pdf fiveparam  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas_fiveparam &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_fiveparam/ -l 971 --xsec 200 --gen-pdf atlas6       --fit-pdf fiveparam  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_atlas6_fiveparam &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_fiveparam/ -l 971 --xsec 200 --gen-pdf silvio5     --fit-pdf fiveparam  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio5_fiveparam &
#python python/PlotBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_fiveparam/ -l 971 --xsec 200 --gen-pdf silvio6     --fit-pdf fiveparam  -b CaloTrijet2016  --mass range\(300,1001,50\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& logPlotBias_silvio6_fiveparam &

