
python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_silvio4 -l 27.637 --xsec 1 --gen-pdf modexp       --fit-pdf silvio4 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_modexp_silvio4 &
python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_silvio4 -l 27.637 --xsec 1 --gen-pdf fiveparam --fit-pdf silvio4 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_fiveparam_silvio4 &
python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_silvio4 -l 27.637 --xsec 1 --gen-pdf atlas         --fit-pdf silvio4 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas_silvio4 &
python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_silvio4 -l 27.637 --xsec 1 --gen-pdf atlas6       --fit-pdf silvio4 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas6_silvio4 &
python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio4_silvio4 -l 27.637 --xsec 1 --gen-pdf silvio4     --fit-pdf silvio4 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio4_silvio4 &
python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_silvio4 -l 27.637 --xsec 1 --gen-pdf silvio5     --fit-pdf silvio4 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio4_silvio4 &
python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_silvio4 -l 27.637 --xsec 1 --gen-pdf silvio6     --fit-pdf silvio4 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio6_silvio4 &

#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_silvio6 -l 27.637 --xsec 1 --gen-pdf modexp       --fit-pdf silvio6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_modexp_silvio6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_silvio6 -l 27.637 --xsec 1 --gen-pdf fiveparam --fit-pdf silvio6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_fiveparam_silvio6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_silvio6 -l 27.637 --xsec 1 --gen-pdf atlas         --fit-pdf silvio6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas_silvio6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_silvio6 -l 27.637 --xsec 1 --gen-pdf atlas6       --fit-pdf silvio6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas6_silvio6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_silvio6 -l 27.637 --xsec 1 --gen-pdf silvio5     --fit-pdf silvio6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio5_silvio6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_silvio6 -l 27.637 --xsec 1 --gen-pdf silvio6     --fit-pdf silvio6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio6_silvio6 &


#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_silvio5 -l 27.637 --xsec 1 --gen-pdf modexp       --fit-pdf silvio5 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_modexp_silvio5 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_silvio5 -l 27.637 --xsec 1 --gen-pdf fiveparam --fit-pdf silvio5 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_fiveparam_silvio5 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_silvio5 -l 27.637 --xsec 1 --gen-pdf atlas         --fit-pdf silvio5 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas_silvio5 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_silvio5 -l 27.637 --xsec 1 --gen-pdf atlas6       --fit-pdf silvio5 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas6_silvio5 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_silvio5 -l 27.637 --xsec 1 --gen-pdf silvio5     --fit-pdf silvio5 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio5_silvio5 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_silvio5 -l 27.637 --xsec 1 --gen-pdf silvio6     --fit-pdf silvio5 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio6_silvio5 &


#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_atlas6 -l 27.637 --xsec 1 --gen-pdf modexp       --fit-pdf atlas6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_modexp_atlas6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_atlas6 -l 27.637 --xsec 1 --gen-pdf fiveparam --fit-pdf atlas6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_fiveparam_atlas6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_atlas6 -l 27.637 --xsec 1 --gen-pdf atlas         --fit-pdf atlas6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas_atlas6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_atlas6 -l 27.637 --xsec 1 --gen-pdf atlas6       --fit-pdf atlas6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas6_atlas6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_atlas6 -l 27.637 --xsec 1 --gen-pdf silvio5     --fit-pdf atlas6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio5_atlas6 &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_atlas6 -l 27.637 --xsec 1 --gen-pdf silvio6     --fit-pdf atlas6 -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio6_atlas6 &



#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/modexp_fiveparam -l 27.637 --xsec 1 --gen-pdf modexp       --fit-pdf fiveparam -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_modexp_fiveparam &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/fiveparam_fiveparam -l 27.637 --xsec 1 --gen-pdf fiveparam --fit-pdf fiveparam -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_fiveparam_fiveparam &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas_fiveparam -l 27.637 --xsec 1 --gen-pdf atlas         --fit-pdf fiveparam -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas_fiveparam &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/atlas6_fiveparam -l 27.637 --xsec 1 --gen-pdf atlas6       --fit-pdf fiveparam -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_atlas6_fiveparam &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio5_fiveparam -l 27.637 --xsec 1 --gen-pdf silvio5     --fit-pdf fiveparam -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio5_fiveparam &
#python python/RunBias.py -c config/dijet_silvio_bias.config -m qq -d signal_bias_silvio/qq/silvio6_fiveparam -l 27.637 --xsec 1 --gen-pdf silvio6     --fit-pdf fiveparam -t 1 -i fits_trijet_silvio_2018/DijetFitResults_CaloTrijet2016.root -b CaloTrijet2016  --mass range\(300,601,10\) --asymptotic-file  cards_qq_freq/xsecUL_Asymptotic_qq_CaloTrijet2016.root >& log_silvio6_fiveparam &
