mkdir -p \Fish_DijetFisherNom3 \Fish_DijetFisherNom4 \Fish_DijetFisherNom5 \Fish_DijetFisherNom6 \Fish_DijetFisherNom7 \Fish_DijetFisherAlt3 \Fish_DijetFisherAlt4 \Fish_DijetFisherAlt5 \Fish_DijetFisherAlt6 \Fish_DijetFisherAlt7 \

    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom3.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherNom3/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherNom3 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom4.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherNom4/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherNom4 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom5.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherNom5/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherNom5 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom6.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherNom6/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherNom6 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom7.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherNom7/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherNom7 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt3.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherAlt3/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherAlt3 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt4.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherAlt4/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherAlt4 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt5.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherAlt5/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherAlt5 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt6.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherAlt6/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherAlt6 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt7.config -l 1992  -b CaloTrijet2016 -d Fish_DijetFisherAlt7/ --fit-spectrum inputs_Danyyl/data_th1f_full_newmethod_cr_4.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logDijetFisherAlt7 & 
##########################################
mkdir -p \FishFullData_DijetFisherNom3 \FishFullData_DijetFisherNom4 \FishFullData_DijetFisherNom5 \FishFullData_DijetFisherNom6 \FishFullData_DijetFisherNom7 \FishFullData_DijetFisherAlt3 \FishFullData_DijetFisherAlt4 \FishFullData_DijetFisherAlt5 \FishFullData_DijetFisherAlt6 \FishFullData_DijetFisherAlt7 \

    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom3.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherNom3/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherNom3 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom4.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherNom4/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherNom4 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom5.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherNom5/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherNom5 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom6.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherNom6/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherNom6 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherNom7.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherNom7/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherNom7 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt3.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherAlt3/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherAlt3 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt4.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherAlt4/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherAlt4 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt5.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherAlt5/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherAlt5 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt6.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherAlt6/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherAlt6 & 
    python python/BinnedFit.py -c config/dijet_isr_DijetFisherAlt7.config -l 21190  -b CaloTrijet2016 -d FishFullData_DijetFisherAlt7/ --fit-spectrum inputs_Danyyl/data_th1f_full_flipped_eta.root --signal inputs/ResonanceShapes_qq_13TeV_CaloScouting_2016.root  --model qq --mass 410 --xsec 20 >& logFullDataDijetFisherAlt7 & 

